[package]
name = "google-translate-scraper"
version = "1.0.0"
edition = "2024"
rust-version = "1.90"
publish = false

[dependencies]
rand = "0.8"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
url = "2"
