export interface TrustedShopsSearchResponse {
    metaData?: {
        totalShopCount?: number;
        totalPageCount?: number;
        [key: string]: unknown;
    };
    shops?: TrustedShopsShop[];
    categories?: TrustedShopsCategory[];
    data?: {
        shops?: TrustedShopsShop[];
        [key: string]: unknown;
    };
    [key: string]: unknown;
}

export interface TrustedShopsCategory {
    name?: string;
    id?: number;
    urlPath?: string;
    totalCount?: number;
    [key: string]: unknown;
}

export interface TrustedShopsShop {
    profileType?: string;
    accountName?: string;
    tsID?: string;
    shopDescription?: string;
    shopName?: string;
    shopUrl?: string;
    shopCategories?: TrustedShopsCategory[];
    shopLogoUrl?: string | null;
    descriptionAutoGenerated?: boolean;
    averageRating?: number;
    reviewCount?: number;
    certificationState?: boolean;
    profileUrl?: string;
    contractStartDate?: number;
    [key: string]: unknown;
}

export function getTrustedShops(response: TrustedShopsSearchResponse): TrustedShopsShop[] {
    const shops = Array.isArray(response.shops) ? response.shops : null;
    if (shops && shops.length > 0) {
        return shops;
    }

    if (Array.isArray(response.data?.shops)) {
        return response.data.shops;
    }

    return shops ?? [];
}

function withProtocol(url: string | undefined): string | null {
    if (!url) {
        return null;
    }

    return /^https?:\/\//i.test(url) ? url : `https://${url}`;
}

export function buildTrustedShopsDatasetItem(
    shop: TrustedShopsShop,
    params: Record<string, unknown>,
    response: TrustedShopsSearchResponse,
): Record<string, unknown> {
    const categories = Array.isArray(shop.shopCategories) ? shop.shopCategories : [];

    return {
        ...shop,
        tsID: shop.tsID ?? null,
        accountName: shop.accountName ?? null,
        shopName: shop.shopName ?? null,
        shopUrl: shop.shopUrl ?? null,
        shop_url: withProtocol(shop.shopUrl),
        profileUrl: shop.profileUrl ?? null,
        profile_url: withProtocol(shop.profileUrl),
        profileType: shop.profileType ?? null,
        shopDescription: shop.shopDescription ?? null,
        shopLogoUrl: shop.shopLogoUrl ?? null,
        averageRating: shop.averageRating ?? null,
        reviewCount: shop.reviewCount ?? null,
        certificationState: shop.certificationState ?? null,
        contractStartDate: shop.contractStartDate ?? null,
        category_names: categories.map((category) => category.name).filter(Boolean).join(', '),
        category_ids: categories.map((category) => category.id).filter((id) => id !== undefined).join(', '),
        category_url_paths: categories.map((category) => category.urlPath).filter(Boolean).join(', '),
        request_q: params.q ?? null,
        request_market: params.market ?? null,
        request_page: params.page ?? null,
        total_shop_count: response.metaData?.totalShopCount ?? null,
        total_page_count: response.metaData?.totalPageCount ?? null,
    };
}
